# Generated by Django 6.0.6 on 2026-06-11 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_type',
            field=models.CharField(choices=[('Academic', 'Academic'), ('Library', 'Library'), ('Hostel', 'Hostel'), ('Cafeteria', 'Cafeteria')], max_length=20),
        ),
    ]
